pipeline:
  name: harness-pipeline
  identifier: harness_pipeline
  projectIdentifier: default_project        
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: harsh43580           
        repoName: Harness-Intigration      
        build: <+input>                     

  stages:
    - stage:
        name: Build and Test
        identifier: Build_And_Test
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Tests
                  identifier: Maven_Tests
                  spec:
                    image: maven:3.9.5-eclipse-temurin-17
                    shell: Sh
                    command: |
                      mvn clean test

              - step:
                  type: Test
                  name: Publish Test Reports
                  identifier: Publish_Test_Reports
                  spec:
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
